# Generated by Django 5.0.4 on 2024-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recently_played',
            field=models.BooleanField(default=False),
        ),
    ]
