# Generated by Django 5.0.4 on 2024-10-01 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_songrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.songrecommendation'),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_images/'),
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='chatapp.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.songrecommendation')),
            ],
            options={
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
