# Generated by Django 5.0.4 on 2024-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_favorite_song_remove_playlist_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrecommendation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
